### PR TITLE
[WiiU] Combined Dockerfile 

### PR DESCRIPTION
**Pull request by qurious-pixel**
Proposal for combining the Dockerfile.

### CODE REVIEW

**Comment by GaryOderNichts** [comment]
The Wii U packages on the pacman repositories are usually several commits behind or missing PRs, which is why the Wii U Dockerfile builds them from source.
wut was updated today, and I'm currently trying to get a new SDL2 version released with important audio bug fixes.
Until that's released it might be better to stick to source builds for SDL2.

**Comment by GaryOderNichts** [comment]
All Wii U packages on the pacman repos should be up-to-date now, so building packages from source is no longer necessary.
Can you point this PR to the [wiiu-upstream-pr](https://github.com/GaryOderNichts/Shipwright/tree/wiiu-upstream-pr) branch, and remove the old `Dockerfile.wiiu`?

**Comment by qurious-pixel** [comment]
I will make the change to the other branch. 
How is the SDL and SDL Audio being handled?
Devkit or source targeting 2.0.9 / 2.0.12.

**Comment by GaryOderNichts** [comment]
> I will make the change to the other branch. How is the SDL and SDL Audio being handled? Devkit or source targeting 2.0.9 / 2.0.12.

The SDL2 version which is part of the pacman wiiu-portlibs group works fine now. It was updated a few hours ago to include a PR with an audio bugfix and is now the same as the one I was building before.

**Pull request closed without merging**
